### ISSUE TITLE
Possible false positive on https://www.coursera.org/ ?

### ISSUE THREAD

**Issue by LeonardoXavier** [ghostwords/chameleon#15]
I have tried using the extension both on and off and when on the coursera pages gives me a notification that i'm using a browser that isn't recognized. With it off i don't get any such notification.

**Comment by ghostwords** [comment]
Coursera considers Firefox 31 to be unsupported. Firefox 31 is what Tor Browser currently uses, and since Chameleon currently attempts to [blend in with Tor](https://github.com/ghostwords/chameleon#protection), you see the unsupported browser message.

We are going to replace masquerading as Tor with randomization (see #1). This kind of problem will then resolve itself since Chameleon for Chrome will probably never want to pretend to be an older version of Firefox.

In the meantime you could disable Chameleon on the Coursera site.

**Comment by LeonardoXavier** [comment]
Is there a way we can change it so that chameleon doesnt change our useragent without breaking anything with it ?

**Comment by ghostwords** [comment]
No, not yet. Let's switch to randomization first.
